-- liquibase formatted sql

-- changeset Nhan Nguyen:MECP-4-1
CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    total_price NUMERIC(19,2) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    modified_on TIMESTAMP NOT NULL,
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_carts_status CHECK (status IN ('ACTIVE'))
);

CREATE INDEX idx_carts_user_status ON carts (user_id, status);
