-- liquibase formatted sql

-- changeset Nhan Nguyen:MECP-17-1
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    total_price NUMERIC(19,2) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    modified_on TIMESTAMP NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_orders_status CHECK (status IN ('CREATED', 'PAID', 'CANCELLED', 'COMPLETED'))
);

CREATE INDEX idx_orders_user_id ON orders (user_id);