-- liquibase formatted sql

-- changeset Nhan Nguyen:MECP-3-1
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price NUMERIC(19,2) NOT NULL,
    sku VARCHAR(100) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    created_on TIMESTAMP NOT NULL,
    modified_on TIMESTAMP NOT NULL,
    CONSTRAINT uk_products_sku UNIQUE (sku),
    CONSTRAINT ck_products_stock CHECK (stock_quantity >= 0)
);

CREATE UNIQUE INDEX idx_products_sku ON products(sku);
